import { Arimo } from "next/font/google";
import "./globals.css";

const arimo = Arimo({
	subsets: ["latin"],
	variable: "--font-arimo",
	weight: ['400', '500', '600', '700'],
});

export const metadata = {
	title: "Mini Quiz Ambis",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
		<head>
			<link 
				href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined"
				rel="stylesheet" 
			/>
		</head>
		<body
			className={`${arimo.variable}`}
		>
		{children}
		</body>
    </html>
  );
}
